### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by UtopiaHu** [flyywh/CVPR-2020-Semi-Low-Light#11]
Hi, 
I've downloaded the dataset via the link you provided. In subfolder 'stage2', four folders are included. Did you train your method in stage 2 using the subfolders 'Low_degraded' and 'Normal' ? And what are subfolders 'AVA_good_2' and 'Low_real_test_2_rs' used for?

**Comment by flyywh** [comment]
More details can be seen in the Detailed Guidance. Many thanks!

**Comment by UtopiaHu** [comment]
> More details can be seen in the Detailed Guidance. Many thanks!

Where can I download LOL-v2 dataset?

**Comment by flyywh** [comment]
You can access the dataset via the links:
Baiduyun: https://pan.baidu.com/s/1Nh2K_CcKr8wWwEzOslDW9w (15iq)
Google Drive: https://drive.google.com/file/d/1dzuLCk9_gE2bFF222n3-7GVUlSVHpMYC/view?usp=sharing
