### ISSUE TITLE
Where is the dataset placed

### ISSUE THREAD

**Issue by anothersin** [flyywh/CVPR-2020-Semi-Low-Light#3]

**Comment by anothersin** [comment]
I am not sure how to place your supplied dataset in the project. I change 13 lines in the data.lowlighTtest file in each stage. 
            13    self.apath = 'Semi-Low-Light/Dataset/stage2/'
However, an error occurred while running STAGE2.test.sh

Evaluation:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main_test.py", line 32, in <module>
    while not t.terminate():
  File "Semi-Low-Light/DRBL-stage2/src/trainer_test.py", line 294, in terminate
    self.test()
  File "Semi-Low-Light/DRBL-stage2/src/trainer_test.py", line 266, in test
    self.ckp.log[-1, idx_scale] = eval_acc / len(self.loader_test)
ZeroDivisionError: division by zero

I tried a lot of things but they didn't work. It would be great if you could suggest a change

**Comment by flyywh** [comment]
Could you try the absolute path?

**Comment by anothersin** [comment]
> Could you try the absolute path?

Unfortunately, I've tried using an absolute path but it leads to the same problem

**Comment by anothersin** [comment]
> Could you try the absolute path?

And I found some paths in your code with your name. But the relevant folder was not found

**Comment by flyywh** [comment]
Could you try modify "self.ext = ('.jpg', '.jpg', '.png', '.jpg')" line 18 based on the file postfix?

**Comment by 13476158779** [comment]
> Hello,have you solved this problem？I met the same problem...

Could you please tell me how did you solve this problem? THANKS
