### ISSUE TITLE
i test some low light images with the pretrained model, and the result seems not good.  did I make an error?

### ISSUE THREAD

**Issue by lulu9449** [flyywh/CVPR-2020-Semi-Low-Light#5]

**Comment by YifeiAI** [comment]
same here. I try to test on  LOL dataset with images 690-789 as described in the paper. However, I was only able to get PSNR of 9.687. The number stated in the paper is 20.13 (Table 1).  Is there anyone else have a similar problem?

**Comment by YifeiAI** [comment]
@flyywh Is it possible that the weight you uploaded for model_R_s2.pt is corrupted? it is only 78kb

**Comment by GuoLanqing** [comment]
Hi, I also meet the same problem. I got PSNR of 11.824. Have you solved the problem? Thanks a lot.

**Comment by flyywh** [comment]
1. First, 20.13 (Table 1) is achieved by the first stage. More details can be seen in the first point of Detailed Guidance.
2. Such low PSNRs are obtained as stage 2's PSNR calculation in stage2-other-datasets (stage2 in the original version) are meaningless as the testing input is unpaired and PSNR calculation is performed based on the enhanced image and original input.

**Comment by flyywh** [comment]
Pytorch需要0.4.0或0.4.1，“cannot import name '_utils'”看起来是MSDataLoader的问题，但我不清楚你使用pytorch0.4.1为什么会遇到这个问题。可以参考其他类似code使用更高版本pytorch的dataloader: https://github.com/sanghyun-son/EDSR-PyTorch
