### ISSUE TITLE
你好请问stage2里lowlighttest.py里的四个文件夹放的分别是什么数据呀，谢谢~

### ISSUE THREAD

**Issue by meihao5631** [flyywh/CVPR-2020-Semi-Low-Light#6]

**Comment by flyywh** [comment]
More details can be seen in the Detailed Guidance.

**Comment by Trueman1997** [comment]
你好请问解决了吗，如果只做测试的话lowlighttest.py对应的四个数据文件夹应该放什么数据呀？

**Comment by flyywh** [comment]
self.dir_hr = os.path.join(self.apath, 'Low_real_test_2_rs')
        self.dir_lr = os.path.join(self.apath, 'Low_real_test_2_rs')
        self.dir_hq = os.path.join(self.apath, 'AVA_good_2')
        self.dir_lrr = os.path.join(self.apath, 'Low_real_test_2_rs')
Please put the testing images in Low_real_test_2_rs and any other images in AVA_good_2.
Please raise a new issue when you have the problem. It is quite confusing to still update the closed one.
