### ISSUE TITLE
Can not download the dataset with provided link

### ISSUE THREAD

**Issue by YifeiAI** [flyywh/CVPR-2020-Semi-Low-Light#7]
Hi,

I tried many ways but couldn't download the dataset with provided link. Would it be possible to have a download link with other platform for example google drive? That would be extremely helpful.

Thanks a lot!!

**Comment by SagArSutAr-crypto** [comment]
Hi,

Even I am facing the same issue please can u provide us the dataset link.

Thanks a lot!!

**Comment by flyywh** [comment]
I have updated the dataset.
