### ISSUE TITLE
Mismatch of dataset numbers

### ISSUE THREAD

**Issue by ZeldaM1** [flyywh/CVPR-2020-Semi-Low-Light#8]
Hi, thanks for sharing your codes.
The LOL dataset in your paper concludes 689 images for training and 100 for testing. But somehow the official dataset released in Retinext: https://daooshee.github.io/BMVC2018website/ concludes only 500 images. Have you augmented experiment data based on LOL dataset?

**Comment by flyywh** [comment]
More details can be seen in the Detailed Guidance. Many thanks!
