### ISSUE TITLE
About Stage2 dataset

### ISSUE THREAD

**Issue by by5747** [flyywh/CVPR-2020-Semi-Low-Light#9]
I have questions about the stage2 dataset.

Did you train stage2 with the synthetic dataset proposed in this paper(Deep Retinex Decomposition for Low-Light Enhancement)?
Also, I am curious about what is "low_real_test_2_rs".

Thank you

**Comment by flyywh** [comment]
More details can be seen in the Detailed Guidance. Many thanks!
